server:
  port: 8080
  sessionTimeout: 30
  contextPath: /mars
  jetty:
    acceptors: 2

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mars?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class: com.mysql.jdbc.Driver
    mail:
        host: smtp.sina.com
        username: stonew1987@sina.com
        password: Sa19870505
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8

mybatis:
 config-location: classpath:mybatis-config.xml

#mybatis:
#  mapper-locations: classpath*:com/mars/**/mapper/*Mapper.xml
#  type-aliases-package: com.mars.*.model
