server:
  port: 8083
  sessionTimeout: 30
  contextPath: /mars
  jetty:
    acceptors: 2

spring:
    datasource:
        url: jdbc:mysql://139.196.199.232:3306/mars?useUnicode=true&characterEncoding=utf-8
        username: root
        password: arm_123456
        driver-class: com.mysql.jdbc.Driver

##mybatis
mybatis:
  config-location: classpath:manage/mapper/mybatis-config.xml